use ELearningPlatform;

INSERT INTO Instructors (instructor_id, instructor_name, expertise_area) VALUES
(1, 'Daniel Brown', 'Sports coach'),
(2, 'Cody Smith', 'Chartered public finance accountant'),
(3, 'Jeffrey Brown', 'Chemical engineer'),
(4, 'Jason Jackson', 'Warehouse manager'),
(5, 'Kelly Thompson', 'Technical sales engineer'),
(6, 'Monique Meyer', 'Estate manager/land agent'),
(7, 'Emily Wright', 'Public house manager'),
(8, 'Robert Williams MD', 'Lexicographer'),
(9, 'Andrea Hanna', 'Paediatric nurse'),
(10, 'Kayla Moyer', 'Garment/textile technologist'),
(11, 'Cynthia Stevens', 'Physiological scientist'),
(12, 'Jennifer Cox', 'Geoscientist'),
(13, 'Kyle Brown', 'Editor, commissioning'),
(14, 'Rachel Griffith', 'Education officer, community'),
(15, 'Andrea Foster', 'Advertising art director'),
(16, 'Amber Jackson', 'Solicitor, Scotland'),
(17, 'Kenneth Johnson', 'Retail manager'),
(18, 'Brian Ramirez', 'Librarian, academic'),
(19, 'Carl Wu', 'Dancer'),
(20, 'Heather Brown', 'Freight forwarder'),
(21, 'Heidi Gibbs', 'Scientist, physiological'),
(22, 'Jennifer Rojas', 'Theme park manager'),
(23, 'Kathryn Reyes', 'Outdoor activities/education manager'),
(24, 'Lauren Ross', 'Public relations officer'),
(25, 'Peter Travis', 'Ship broker'),
(26, 'Melissa Williams', 'Public affairs consultant'),
(27, 'Anna Clark', 'Physiotherapist'),
(28, 'Ryan Cole', 'Clinical scientist, histocompatibility and immunogenetics'),
(29, 'Kelsey Turner', 'Television production assistant'),
(30, 'Ashley Clark', 'Civil engineer, contracting'),
(31, 'Alexandra Alvarado', 'Electronics engineer'),
(32, 'Mrs. Sarah Gonzales', 'Public relations officer'),
(33, 'Jonathan Mcpherson', 'Consulting civil engineer'),
(34, 'Amanda Dunn', 'Medical technical officer'),
(35, 'Mr. Ryan Smith II', 'Geophysical data processor'),
(36, 'Kevin Werner', 'Clothing/textile technologist'),
(37, 'James Gordon', 'Pharmacist, hospital'),
(38, 'Megan Larson', 'Midwife'),
(39, 'Michelle Hamilton', 'Maintenance engineer'),
(40, 'Melvin Crawford', 'Science writer');